---
# Needed when we want ssh over gitlab.example.me while hostname is othername.example.me
# sshd refuse the connection

- name: Add a line to allow ssh over the subdomain
  lineinfile: >
    state=present
    dest=/etc/hosts
    regexp='^127.0.1.1'
    line="127.0.1.1 {{ gitlab_setup_host_domain }}"
  when: gitlab_setup_host_domain and gitlab_setup_host_domain != ansible_hostname


# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Create GitLab SSL configuration folder.
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: gitlab_create_self_signed_cert

- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "{{ item.self_signed_cert_subj }}" -days 3650 -keyout {{ item.ssl_certificate_key }} -out {{ item.ssl_certificate }} -extensions v3_ca
    creates={{ item.ssl_certificate }}
  register: certs
  when: gitlab_create_self_signed_cert
  with_items:
    - self_signed_cert_subj: "{{ gitlab_self_signed_cert_subj }}"
      ssl_certificate_key: "{{ gitlab_ssl_certificate_key }}"
      ssl_certificate: "{{ gitlab_ssl_certificate }}"
    - self_signed_cert_subj: "{{  gitlab_mattermost_self_signed_cert_subj }}"
      ssl_certificate_key: "{{ gitlab_mattermost_ssl_certificate_key }}"
      ssl_certificate: "{{ gitlab_mattermost_ssl_certificate }}"
  notify:
    - restart gitlab
    - update ca-store
    - restart nginx

- name: Copy certificate to linux ca certificates folder
  command: cp {{ item.item.ssl_certificate }} {{ gitlab_linux_ca_certificates_dir }}/
  when: item | changed
  with_items: certs.results

- name: Configure ca-certificates tools
  lineinfile: >
    dest="{{ gitlab_linux_ca_certificates_conf }}"
    regexp="^{{ item.item.ssl_certificate | basename }}"
    line="{{ item.item.ssl_certificate | basename}}"
    state=present
  when: item | changed
  with_items: certs.results

- name: Copy GitLab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab

- name: Ensure backups dir exist
  file: >
    state=directory
    path=/var/opt/gitlab/backups
    mode='u=rwx,g=,o='
    owner=git
    group=root
