---

# Install GitLab and its dependencies (RedHat).
- name: Install GitLab dependencies (RedHat).
  yum: "name={{ item }} state=installed"
  with_items: gitlab_dependencies
  when: ansible_os_family == 'RedHat'

- name: Download GitLab repository installation script (RedHat).
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh

- name: Install GitLab repository (RedHat)
  command: bash /tmp/gitlab_install_repository.sh
  notify: migrate database

- name: Install GitLab (RedHat)
  yum: "name=gitlab-ce state=installed"
