---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- include: install_debian.yml
  when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'Debian')

- include: install_redhat.yml
  when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'RedHat')

- include: configure.yml
