---
- name: restart gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when

- name: migrate database
  command: gitlab-rake db:migrate
  when: gitlab_restart_handler_failed_when

- name: update ca-store
  command: update-ca-certificates

- name: restart nginx
  command: gitlab-ctl restart nginx
